#!/usr/bin/env php
<?php
include __DIR__ . "/ApiRequester/Client.php";

if (count($argv) < 2) {
	echo "Missing mandatory parameter: location of options file.\n";
	exit(2);
}

$r = new helvete\ApiRequester\Client($argv[1]);
$request = $r->request();
$httpCode = key($request);
$response = current($request);
$key = "RESPONSE [{$httpCode}]";
$iterate = array(
	'REQUEST' => $r->getReqStr(),
	$key => $response,
);

$exact = $noJson = false;
for ($i = 1; $i < count($argv); $i++) {
	switch ($argv[$i]) {
	case '--exact-return':
		$exact = true;
		break;
	case '--non-json':
		$noJson = true;
		break;
	}
}
if ($exact) {
	echo $iterate[$key];
	exit(0);
}

$embed = '';
foreach ($iterate as $name => $data) {
	echo "{$embed}{$name}:\n";
	if ($noJson) {
		echo $data;
	} else {
		print_r(
			json_encode(
				json_decode($data, true),
				JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES
			)
		);
	}
	$embed = "\n";
}
echo "\nBye!\n";
